function tests = ConformanceTest
% CONFORMANCETEST Pin the contract between this repository and the main
% lts repository (contract items 1-3 of the repository split; see the
% Contracts page of the main repository's documentation).
%
%  1. cfg schema — lts.components.Suspension.validateConfig accepts the
%     canonical cfg.suspension and rejects bad input with typed errors.
%  2. Interface — SuspensionManager subclasses SuspensionComponent and
%     satisfies the structural probes SimpleChassis performs.
%  3. Telemetry producer fields — the SuspensionState property names
%     below are mapped 1:1 onto per-corner telemetry channels by the
%     main repository's StateLogBuilder. Renaming any of them is a
%     contract change: update this test and the Contracts page in the
%     same PR, then coordinate the main-repository change (see
%     "Changing the contract" there).
tests = functiontests(localfunctions);
end

function cfg = canonicalConfig()
% Mirrors the baseline cfg.suspension from the main repository's
% VehicleConfig (including the geometry sub-struct).
cfg = struct( ...
    'front', struct('springRate', 45000, 'dampingCoeff', 3000, ...
    'reboundCoeff', 4500), ...
    'rear',  struct('springRate', 42000, 'dampingCoeff', 2800, ...
    'reboundCoeff', 4200), ...
    'motionRatio', 0.95, ...
    'bumpStopLength', 0.025, ...
    'bumpStopRate', 200000, ...
    'tireSpringRate', 200000, ...
    'dampingKneeSpeed', 0.05, ...
    'dampingHighSpeedRatio', 0.3, ...
    'dampingReboundKneeSpeed', NaN, ...
    'frontArb', struct('stiffness', 1800, 'motionRatio', 0.95, ...
    'leverArm', 0.26, 'enabled', true), ...
    'rearArb',  struct('stiffness', 1100, 'motionRatio', 0.95, ...
    'leverArm', 0.26, 'enabled', true), ...
    'rollStiffnessOverride', NaN, ...
    'coupleChassisRollToLoadTransfer', false);
cfg.geometry = struct( ...
    'front', struct( ...
        'travelGrid',       [-0.05 0 0.05], ...
        'camberCurve',      [0.5 0 -1.5] * pi / 180, ...
        'toeCurve',         [-0.05 0 0.05] * pi / 180, ...
        'motionRatioCurve', [0.93 0.95 0.97], ...
        'rollCenterHeight', 0.030), ...
    'rear', struct( ...
        'travelGrid',       [-0.05 0 0.05], ...
        'camberCurve',      [0.25 0 -0.8] * pi / 180, ...
        'toeCurve',         [0.05 0 -0.05] * pi / 180, ...
        'motionRatioCurve', [0.94 0.95 0.96], ...
        'rollCenterHeight', 0.045), ...
    'steering', struct( ...
        'steeringRatio',      1.0, ...
        'ackermann',          0.8872, ...
        'maxWheelSteerAngle', 0.6));
end

%% ---- 1. Config schema --------------------------------------------------

function testValidateConfigAcceptsCanonicalConfig(testCase)
verifyTrue(testCase, ...
    lts.components.Suspension.validateConfig(canonicalConfig()));
end

function testValidateConfigRejectsMissingArbField(testCase)
cfg = canonicalConfig();
cfg.rearArb = rmfield(cfg.rearArb, 'leverArm');
verifyError(testCase, ...
    @() lts.components.Suspension.validateConfig(cfg), ...
    'lts_suspension_validateConfig:MissingField');
end

function testValidateConfigRejectsNegativeSpringRate(testCase)
cfg = canonicalConfig();
cfg.front.springRate = -45000;
verifyError(testCase, ...
    @() lts.components.Suspension.validateConfig(cfg), ...
    'lts_suspension_validateConfig:OutOfRange');
end

function testValidateConfigRejectsZeroMotionRatio(testCase)
cfg = canonicalConfig();
cfg.motionRatio = 0;
verifyError(testCase, ...
    @() lts.components.Suspension.validateConfig(cfg), ...
    'lts_suspension_validateConfig:OutOfRange');
end

function testValidateConfigRejectsBadRollStiffnessOverride(testCase)
cfg = canonicalConfig();
cfg.rollStiffnessOverride = 1.5;
verifyError(testCase, ...
    @() lts.components.Suspension.validateConfig(cfg), ...
    'lts_suspension_validateConfig:OutOfRange');
end

function testValidateConfigRejectsMissingGeometry(testCase)
cfg = canonicalConfig();
cfg = rmfield(cfg, 'geometry');
verifyError(testCase, ...
    @() lts.components.Suspension.validateConfig(cfg), ...
    'lts_suspension_validateConfig:InvalidGeometry');
end

%% ---- 2. Interface (contract item 1) -------------------------------------

function testManagerSubclassesSuspensionComponent(testCase)
mc = meta.class.fromName( ...
    'lts.components.Suspension.SuspensionManager');
supers = {mc.SuperclassList.Name};
verifyTrue(testCase, ...
    any(endsWith(supers, 'SuspensionComponent')), ...
    'SuspensionManager must subclass SuspensionComponent.');
end

function testManagerSatisfiesChassisStructuralProbes(testCase)
% SimpleChassis.setSuspension gates on these structural capabilities —
% no class-name coupling in either direction.
vm = struct('totalMass', 264, 'wheelbase', 1.558, 'trackWidth', 1.21, ...
    'cgHeight', 0.30, 'staticFrontWeight', 0.5038, 'g', 9.80665);
mgr = lts.components.Suspension.SuspensionManager(vm, ...
    43780, 3500, 4000, 39400, 3200, 3600, 1.0, ...
    0.03, 350000, 190000, 9.3);
probes = {'getAxleRollStiffness', 'warmup', ...
    'computeCornerLoadsFromChassis', 'computePitchAngle', ...
    'getCornerKinematics'};
for i = 1:numel(probes)
    verifyTrue(testCase, ismethod(mgr, probes{i}), ...
        sprintf('SuspensionManager must implement %s.', probes{i}));
end
end

%% ---- 3. Telemetry producer fields (contract item 3) ---------------------

function testSuspensionStatePinsTelemetryFieldNames(testCase)
% Exact property names StateLogBuilder maps onto per-corner channels
% (damperPos_FL <- damperPosition, damperVel_FL <- damperVelocity,
% camber_FL <- camberAngle, Fz_FL <- tireNormalForce, ...).
mc = meta.class.fromName('lts.components.Suspension.SuspensionState');
props = {mc.PropertyList.Name};
required = {'damperPosition', 'damperVelocity', 'tireDeflection', ...
    'sprungPosition', 'sprungVelocity', ...
    'unsprungPosition', 'unsprungVelocity', ...
    'wheelTravel', 'camberAngle', 'toeAngle', 'steerAngle', ...
    'tireNormalForce', 'suspensionForce', 'antiRollBarForce', ...
    'demandedLoad'};
for i = 1:numel(required)
    verifyTrue(testCase, ismember(required{i}, props), ...
        sprintf('SuspensionState must keep property %s.', required{i}));
end
end

function testManagerCornerPropertyNamesPinned(testCase)
% StateLogBuilder reaches the per-corner state through exactly these
% property names (mapped to telemetry corners FL/FR/RL/RR).
mc = meta.class.fromName( ...
    'lts.components.Suspension.SuspensionManager');
props = {mc.PropertyList.Name};
required = {'frontLeft', 'frontRight', 'rearLeft', 'rearRight'};
for i = 1:numel(required)
    verifyTrue(testCase, ismember(required{i}, props), ...
        sprintf('SuspensionManager must keep corner property %s.', ...
        required{i}));
end
end
